### ISSUE TITLE
Feature Request: 

### ISSUE THREAD

**Issue by Sidneys1** [Ebonsignori/obsidian-at-symbol-linking#12]
Expanding on the features added in #6, when creating a new contact from a template, could we get some features like the "Templates" core plugin where it'll expand `{{variables}}` upon copying the template?

For example, if my template file contains:

```md
---
aliases: []
---

# {{title}}
```

And I create a new contact, "`@Sidneys1`", I'd expect the template to be cloned to a new file named `Sidneys1` with the content:

```md
---
aliases: []
---

# Sidneys1
```

**Comment by Ebonsignori** [comment]
You could accomplish this with https://github.com/SilentVoid13/Templater and enabling this setting,
![image](https://github.com/Ebonsignori/obsidian-at-symbol-linking/assets/17055832/e3834dd4-729a-48c1-af3c-70b6594f38b7)
Then in your template you can have `<% tp.file.title %>` and it will be replaced by the filename.

But, I think this is worth supporting the same 3 variables that the core templates function supports in this plugin.

Added in https://github.com/Ebonsignori/obsidian-at-symbol-linking/releases/tag/1.4.4

Thanks for the suggestion!
