### ISSUE TITLE
When I disable 'Include @ symbol' why create an alias?

### ISSUE THREAD

**Issue by stoweboyd** [Ebonsignori/obsidian-at-symbol-linking#14]
I have disabled `Include @ symbol`. But when I create an at-mention by typing `@some name` and then elsect a name or new name from the pop-up, I get the text `[[some name|some name]]`. Why not just `[[some name]]`?

**Comment by Ebonsignori** [comment]
Does the [[name|name]] persist when you press space? 

In case you don't know, the [[path|name]] format is how markdown wiki style links work. The left of the | is the path, the right is the text to display (alias). 

I'm guessing you have "Use [[Wikilinks]]" links enabled in the native Obsidian settings under the "Files & Links" tab. You can turn it off to use markdown links instead

**Comment by redactedscribe** [comment]
I agree with the issue. It's odd that display text is given to a new note created via this plugin.

> Does the [[name|name]] persist when you press space?

`@name` -> Enter -> Space. Yes.


> Try linking by typing `[[`. Is the final result the same as if you used this plugin to link?

No. Via wikilink the result is `[[name]]` which is expected.

**Comment by Ebonsignori** [comment]
This makes sense! I was forcing an `alias` / link text when it wasn't necessary (e.g. not including the `@` symbol). Should be fixed in the latest version!
