### ISSUE TITLE
Don't strip commas when creating a new note

### ISSUE THREAD

**Issue by tht** [Ebonsignori/obsidian-at-symbol-linking#15]
Hi,
IMHO, your plugin significantly improves working with people in Obsidian. Thank you!

However, there is a minor issue that continues to bother me. I prefer my people-notes to be in the format "lastName, firstName", and I write them in this way when using your plugin. For instance, I type "@Skywalker, Anakin" and then press Enter to create a new note.

The newly created note is named "Skywalker Anakin", with the comma missing. As a result, I always have to rename the file and adjust the title within the file, which is somewhat inconvenient. I would greatly appreciate it if the new note could be named exactly as I typed it after the '@' symbol.

**Comment by Ebonsignori** [comment]
Good catch! Should be fixed in [1.4.9](https://github.com/Ebonsignori/obsidian-at-symbol-linking/releases/tag/1.4.9)
