### ISSUE TITLE
Feature request: support custom symbols too

### ISSUE THREAD

**Issue by Rhydderch** [Ebonsignori/obsidian-at-symbol-linking#16]
Hi,

Thank you for this amazing plugin that improves the UX of obsidian.
As pandoc citekeys for references use the @ symbol (e.g., [@Barret2013]), I renamed all my people notes with the + symbol instead. 

Therefore, I was wondering whether you would you consider adding support for custom symbols?

In this way if I type + or ++, I can get all the people suggestions, if I do $ I can get all my projects notes suggestions, etc. 

All the best,
Rhydderch

**Comment by Rhydderch** [comment]
Note: in this way, we could also still use the plugin without the compatibility mode as the symbols wouldn't conflict with the tasks plugin

**Comment by Ebonsignori** [comment]
Good idea! Added in [1.4.9](https://github.com/Ebonsignori/obsidian-at-symbol-linking/releases/tag/1.4.9)
