### ISSUE TITLE
People suggestions list doesn't stay open if @person mid sentence

### ISSUE THREAD

**Issue by redactedscribe** [Ebonsignori/obsidian-at-symbol-linking#17]
If typing @ mid sentence, the people suggestion list is shown but as soon as you start typing, it disappears: `One @pers two`. This means you cannot narrow down the list and then choose a person/name to complete. It also means that you cannot create a new person because the "Create new note" option won't display.

If typing @ and the line's end, you'll notice that the suggestion list remains open and functions as intended while you partially type a name.

Thanks.

**Comment by Ebonsignori** [comment]
I'm sorry but I'm unable to recreate this from these details. 

Are you saying when you type a space the popup closes? You can set the "Leave popup open for X spaces" to `1` or more to prevent this behavior

**Comment by redactedscribe** [comment]
What I mean is: Type `test test` then insert your cursor after the first test, then type space and then @: `test @ test`. At this point to popup opens, but adding any letters after the @ immediately closes the suggestion list:

![Obsidian_2023-10-28_12-57-43](https://github.com/Ebonsignori/obsidian-at-symbol-linking/assets/25013746/321f0c15-619d-42de-85c0-d26ba690cc1a)

Only when @ is at the end of a sentence (meaning it's not between any text) does the suggestion list open when typing letters after @:

![Obsidian_2023-10-28_12-59-31](https://github.com/Ebonsignori/obsidian-at-symbol-linking/assets/25013746/4d27a95e-44cb-46d3-8ff8-7b7439725fdc)

If I increase the X spaces option from 0 to 10 for example, I get what should be the default behaviour:

![Obsidian_2023-10-28_13-02-36](https://github.com/Ebonsignori/obsidian-at-symbol-linking/assets/25013746/abb460b9-ac0c-4d9d-8851-c9754b016b90)

This is with the latest version recently release.

**Comment by jasal82** [comment]
Yep same problem here. Doesn't work when there is preceding text. It seems the number of spaces before the @ is also included in the X spaces.

**Comment by redactedscribe** [comment]
@jasal82 Since commenting, I've set _Leave popup open for X spaces_ to `3` and had less problems.

**Comment by Ebonsignori** [comment]
Sorry about this one. Should be fixed in the latest release, `1.6.2`

Turns out it was just a one line fix 😅 it was trying to look at an additional character which is often just a space, " " in the middle of a sentence so the popup thinks it needs to close unless you have the ` Leave popup open for X spaces` option set high enough to account for the additional space character it picked up
