### ISSUE TITLE
Suggestion popup should persist after `backspace` if characters remain after trigger symbol

### ISSUE THREAD

**Issue by redactedscribe** [Ebonsignori/obsidian-at-symbol-linking#19]
Currently when you, for example, backspace into a @-word, the suggestions are not shown. It would be nice if they'd immediately pop up: `@name` -> backspace the `e` -> `@nam` (no suggestions shown).

Similarly, if clicking into a @-word and starting to type, suggestions could immediately appear.

Thanks.

**Comment by Ebonsignori** [comment]
Thank you for reporting! This is certainly a bug that I'll try to get to next weekend

**Comment by Ebonsignori** [comment]
Haven't been able to recreate this one. Think it may be fixed in both modes
