### ISSUE TITLE
Not working in properties/yaml frontmatter

### ISSUE THREAD

**Issue by quintrino** [Ebonsignori/obsidian-at-symbol-linking#22]
It looks like this works in general text areas, but currently doesn't work in property/frontmatter/yaml. 

![image](https://github.com/Ebonsignori/obsidian-at-symbol-linking/assets/7043587/784c09be-ec65-4904-b0fb-3362b4c9a4c7)

Not sure if this is fixable, but raising it just in case. :)

**Comment by Ebonsignori** [comment]
There isn't a way to get this to work in regular mode in frontmatter, but enabling the `compatibility mode` option should let you link in properties
