### ISSUE TITLE
Trigger don’t work

### ISSUE THREAD

**Issue by pjamin** [Ebonsignori/obsidian-at-symbol-linking#24]
Hi,
on my configuration the trigger does not trigger. 
I tried several values: &, -. 
it still does not work.
Sincerely,

**Comment by Ebonsignori** [comment]
Hi I can't seem to recreate this, though I did recreate another bug where typing the trigger character when it isn't an `@` doesn't show the popup menu unless you type more characters. This should be fixed now.

If you're still experiencing this bug please respond with what operating system you're using.
