### ISSUE TITLE
Accented characters not handled

### ISSUE THREAD

**Issue by lebigot** [Ebonsignori/obsidian-at-symbol-linking#26]
Typing something like `@vérin` will _not_ match VÉRIN fully: the "É" is not highlighted by @ Symbol Linking. This makes matches less relevant, in general, as some letters are simply not matched.

I can suggest two options:
1. Fix this bug: "é" should match "É", etc.
2. Make finding names with accents faster by making matches forget about accents, etc. ("c" would match "ç", "e" would match both "é" and "É", etc.).

What do you think?

**Comment by Ebonsignori** [comment]
@lebigot thank you for reporting. Sort of went with both of your suggestions.

In normal mode, with the new `Remove accents from search query` option off, `é` should match `É`

In compatibility mode I could not find an easy way to parse keyboard events into accented characters.

But by default this option is on in both modes and let's you go with your suggested option `2`, letting you match unaccented `e` to `é` or `É`

All of the above is in [v1.6.1](https://github.com/Ebonsignori/obsidian-at-symbol-linking/releases/tag/1.6.1)
