### ISSUE TITLE
@-mentioning stops working in tasks as soon as it includes #todo

### ISSUE THREAD

**Issue by barryvan** [Ebonsignori/obsidian-at-symbol-linking#3]
It seems as though there's a conflict between this plugin and the Tasks plugin. I have my Tasks plugin setup with a global filter of `#todo`. It seems that as soon as this tag is included in a regular task, @-linking completely stops working on that line.

Attached is a brief video:
https://github.com/Ebonsignori/obsidian-at-symbol-linking/assets/124363/6c5dc0ca-2a91-49e5-a16d-e259ba5ac031

It works fine with other tags -- it just seems to be the specific global filter tag that causes issues.

Steps to reproduce:
1. Install this plugin.
2. Install Tasks.
3. Configure Tasks to use a global filter -- for example, of `#todo`.
4. Create a task list item. Note that @-linking works beautifully.
5. Add the `#todo` tag to the item. Note that now you cannot @-link anywhere on that line until the tag is removed.

**Comment by Ebonsignori** [comment]
Hi @barryvan first off, thank you SO much for pulling this down and using it. Even more so for reporting bugs ❤️ 

Was able to fix the other issue you opened, but having trouble with this.

I've tried following the steps you listed but am able to keep @-linking after typing the global filter, `#todo` which I added in the Tasks plugin options.

If you try updating the tasks plugin to the latest version does it still happen?

If so, mind sharing the following so I can try other ways to reproduce?
- The rest of your Tasks settings
- @ symbol linking settings
- Operating system (I'm assuming Mac OS based on your screenshare which is what I'm testing on too)
- Obsidian version

**Comment by barryvan** [comment]
I think I've worked out what's causing this: the Task plugin's auto-suggest capabilities. Specifically if it's set to "on" and the "length" option is greater than 0. I've worked around this for now by dropping it back to 0. I'm not quite sure how we could go about getting the two working together, so perhaps this is more just something to be aware of if other people run into the issue. :) For now I've just set my own settings such that it's not an issue any more. 😃

**Comment by barryvan** [comment]
Hmm, that's strange! Your settings look like they match mine exactly, so I don't know why it would be working for me and not for you, @judisohn. I think @Ebonsignori is investigating in #7, and I'll also try and have a poke around if I get a chance.

In the meantime, it may be worthwhile trying to force the plugins to load in a different order... I _think_ you can do this by (for example) disabling A then B, then enabling B then A -- but you may need to experiment, and I have about 5% confidence that this will help. 😕 

FWIW, I've also started a discussion over on the Tasks plugin's repo to see if anyone has insights: https://github.com/obsidian-tasks-group/obsidian-tasks/discussions/2239

**Comment by claremacrae** [comment]
There is a workaround for this given in:

- https://github.com/saibotsivad/obsidian-at-people/issues/6#issuecomment-1694767072

**Comment by Ebonsignori** [comment]
@judisohn @barryvan I've added "Compatibility Mode" in [1.4.0](https://github.com/Ebonsignori/obsidian-at-symbol-linking/releases/tag/1.4.0) which should allow the `@` to trigger a link in a task. Please try it out and let me know if you run into any bugs!

**Comment by judisohn** [comment]
@Ebonsignori It works well now! Thank you so much for implementing this quickly. :-)
