### ISSUE TITLE
This seems to conflict with the Tasks plugin autocomplete

### ISSUE THREAD

**Issue by califa** [Ebonsignori/obsidian-at-symbol-linking#7]
Not sure how to solve this: @ doesn't work on tasks, but it does everywhere else.

<img width="91" alt="image" src="https://github.com/Ebonsignori/obsidian-at-symbol-linking/assets/602352/28f9cdb6-0826-4a9d-81d4-f75d29b9abda">

**Comment by Ebonsignori** [comment]
Same as https://github.com/Ebonsignori/obsidian-at-symbol-linking/issues/3#issuecomment-1687312938 but I'll look into a solution.

This happens when you have the auto complete enabled for tasks

**Comment by califa** [comment]
Yep, I find that in itself fairly annoying though since it's triggered on characters and not on a specific symbol. Any way to have an auto-complete threshold for anything but `@`?

**Comment by claremacrae** [comment]
There is a workaround for this given in:

- https://github.com/saibotsivad/obsidian-at-people/issues/6#issuecomment-1694767072

**Comment by Ebonsignori** [comment]
Added "Compatibility Mode" in [1.4.0](https://github.com/Ebonsignori/obsidian-at-symbol-linking/releases/tag/1.4.0) which should allow the `@` to trigger a link in a task. Let me know if you run into any bugs!

**Comment by califa** [comment]
Thanks so much! @Ebonsignori @claremacrae - you're both having such a positive impact on my ADHD life

**Comment by califa** [comment]
The plugin loading order worked perfectly and is fairly straightforward. 

**Bug:** I also tried the "compatibility mode" but after using it once it messed up some of my other keys (`cmd-,` didn't work for options, the `return` key didn't work for newlines).

**Comment by claremacrae** [comment]
I'm going to Unsubscribe from this now, as I don't believe it needs my attention - and I have nothing more to contribute...
